[tool.poetry]
name = "steel-defect-detector"
version = "3.11"
description = ""
authors = ["Michael Wolff <michael.wolff4@gmx.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
